### ISSUE TITLE
[data_tables] Error with web

### ISSUE THREAD

**Issue by Ionys320** [rodydavis/plugins#79]
## Steps to Reproduce
Just use NativeDataTable.builder widget in a web project and run it, even if there is no item.

## Logs
```
[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following JSNoSuchMethodError was thrown building NativeDataTable(dirty, dependencies: [MediaQuery]):[39;49m
TypeError: collection is not iterable

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;248maddAll] (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart:188:17)[39;49m
[38;5;248mbuild[39;49m
[38;5;244mbuild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
TypeError: collection is not iterable
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
TypeError: collection is not iterable
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244mperformRebuild[39;49m
[38;5;244mrebuild[39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244m[_firstBuild][39;49m
[38;5;244mmount[39;49m
[38;5;244minflateWidget[39;49m
[38;5;244mupdateChild[39;49m
[38;5;244m<fn>[39;49m
[38;5;244mbuildScope[39;49m
[38;5;244m[_layout][39;49m
[38;5;244m<fn>[39;49m
[38;5;244m[_enableMutationsToDirtySubtrees][39;49m
[38;5;244minvokeLayoutCallback[39;49m
[38;5;244mlayoutAndBuildChild[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244mlayout[39;49m
[38;5;244mperformLayout[39;49m
[38;5;244m[_layoutWithoutResize][39;49m
[38;5;244mflushLayout[39;49m
[38;5;244mdrawFrame[39;49m
[38;5;244mdrawFrame[39;49m
[38;5;244m[_handlePersistentFrameCallback][39;49m
[38;5;244m[_invokeFrameCallback][39;49m
[38;5;244mhandleDrawFrame[39;49m
[38;5;244m<fn>[39;49m
[38;5;248minternalCallback (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart:50:19)[39;49m
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: TypeError: collection is not iterable

```

```
Analyzing backoffice...

   info - Don't explicitly initialize variables to null - lib\classes\notification.dart:14:7 - avoid_init_to_null
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\variables.dart:1:1 - avoid_web_libraries_in_flutter

2 issues found. (ran in 44.9s)
```

```
Flutter 1.13.6-pre.25 • channel master • https://github.com/flutter/flutter.git
Framework • revision b7af5e714d (8 hours ago) • 2019-12-25 23:49:55 -0800
Engine • revision 33813929e3
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.13.6-pre.25, on Microsoft Windows [version 10.0.18363.535], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio CommunityÂ 2019 16.4.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.34.0)
[√] VS Code, 64-bit edition
[√] Connected device (3 available)

• No issues found!
exit code 0
```

**Comment by onurc4kir** [comment]
Can you fix it ? Same problem.

**Comment by rodydavis** [comment]
Woah weird... I am using the flutter table and rows under the hood. Surely they have support for web?

**Comment by rodydavis** [comment]
Fixed on version 1.0.3

**Comment by surveshoeb** [comment]
@rodydavis still having the same issue in version 1.0.3

> The following JSNoSuchMethodError was thrown building LayoutBuilder:
TypeError: collection is not iterable
The relevant error-causing widget was:
  LayoutBuilder

**Comment by guilhermefc** [comment]
> @rodydavis still having the same issue in version 1.0.3
> 
> > The following JSNoSuchMethodError was thrown building LayoutBuilder:
> > TypeError: collection is not iterable
> > The relevant error-causing widget was:
> > LayoutBuilder

+1

**Comment by klihonga11** [comment]
Same here, just started Flutter web and can't seem to get this to work
